- build.gradle
- src/main/java/com/example/gasip/GasipApplication.java
- src/main/java/com/example/gasip/dto/ProfessorDto.java
- src/main/java/com/example/gasip/entity/ProfessorEntity.java
- ProfessorEntity 개발
- #6 
- 1) setter 를 사용하지 않기 위한 방안 고려
- 2) 데이터 무결성을 보장하기 위해 JPA에서 활용하는 객체 & mvc 단에서 활용하는 객체 분리 필요
- 1) 생성자 방식으로 개발
- 2) JPA : protected 접근 제한자가 달린 기본 생성자 활용
- 2) mvc : of메서드 활용(생성자와 기능 동일)
> Feature/#6 교수목록 entity

- build.gradle
- src/main/java/com/example/gasip/dto/ProfessorDto.java
- src/main/java/com/example/gasip/entity/ProfessorEntity.java
- src/main/java/com/example/gasip/repository/ProfessorRepository.java
- ProfessorDto 개발
- #7 
- dto 내 활용되는 메서드 확립 필요
- 추후 필요 메서드 발생 시 추가
> Feature/#7 교수목록 dto

- src/main/java/com/example/gasip/dto/ProfessorDto.java
> Feat : ProfessorDto 변경

- build.gradle
- src/main/java/com/example/gasip/Board/dto/BoardCreateRequest.java
- src/main/java/com/example/gasip/Board/dto/BoardCreateResponse.java
- src/main/java/com/example/gasip/Board/dto/BoardReadResponse.java
- src/main/java/com/example/gasip/Board/dto/BoardUpdateRequest.java
- src/main/java/com/example/gasip/Board/dto/BoardUpdateResponse.java
boardDTO 개발
#32 
Entity가 현재 없으므로 fromEntity, toEntity 기능 구현 불가
#31 브랜치 생성하여 엔티티 개발 후 기능 구현
> Feature/#32 board dto개발

- src/main/java/com/example/gasip/Board/dto/BoardCreateRequest.java
- src/main/java/com/example/gasip/Board/dto/BoardCreateResponse.java
- src/main/java/com/example/gasip/Board/dto/BoardReadResponse.java
- src/main/java/com/example/gasip/Board/dto/BoardUpdateRequest.java
- src/main/java/com/example/gasip/Board/dto/BoardUpdateResponse.java
- src/main/java/com/example/gasip/Board/model/Board.java
- src/main/java/com/example/gasip/professordetail/model/ProfessorDetail.java
fromEntity, toEntity 구현 완료
Entity클래스 구현 완료
#31
> Feat: Board Entity 개발

- src/main/java/com/example/gasip/professor/controller/ProfessorController.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
professor findAll() 메서드 반환타입 변경(엔티티 -> dto)
반환타입 변경으로 서비스 레이어에서 for-each문 활용
#49 
for-each문을 활용했기에 모든 교수정보를 for문으로 돌려야하는 비효율 발생
1. 교수정보 개수가 성능에 영향을 줄만큼 많은 정보가 아닌, 한정된 개수이므로 그대로 진행
2. 다른 최적화 방안 찾을 것
> Refactor: Professor 전체조회 서비스 로직 리팩토링

- src/main/java/com/example/gasip/major/model/Major.java
- src/main/java/com/example/gasip/professor/dto/ProfessorDto.java
- src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
- src/main/java/com/example/gasip/professor/model/Professor.java
- src/main/java/com/example/gasip/professordetail/dto/ProfessorDetailResponse.java
- src/main/java/com/example/gasip/professordetail/model/ProfessorDetail.java
- Major 엔티티 추가
- professor도메인 DTO & Entity 리팩토링 진행
#55 
Major 엔티티 추가에 따른 professor,professorDetail 도메인 수정 시 DuplicateMappingException 발생
professor,professorDetail 엔티티 둘 다 Major를 파라미터로 받도록 수정
https://hyem5019.tistory.com/entry/Gasip-Project-%EC%99%9C-Column-Name%EC%9D%B4-%EC%A4%91%EB%B3%B5%EC%9D%B4%EB%9D%BC%EA%B3%A0-%EB%9C%A8%EC%A3%A0-DuplicateMappingException
> Feature/#55 엔티티수정

- src/main/java/com/example/gasip/board/model/Board.java
- Board 엔티티에 @DynamicInsert 어노테이션 추가
#66
> Feat: likeCount,clickCount 초기값 0으로 설정

- Gasip Front/App.js
- Gasip Front/Components/HomeStack.js
- Gasip Front/Components/MyPageScreen.js
- Gasip Front/Components/MyPageStack.js
- Gasip Front/Components/SignUpPage.js
- Gasip Front/Components/SplashScreen.js
- Gasip Front/Layout/layout.js
- Gasip Front/app.json
- Gasip Front/eas.json
- Gasip Front/package-lock.json
- Gasip Front/package.json
- Gasip Front/reducers/AuthStore.js
- Gasip Front/reducers/Authentication.js
- Gasip Front/reducers/reducer.js
- 로그인 및 회원가입을 위한 Redux 스택의 도입
#83 
- React.Context를 사용하여 구현하려했으나, 전역적 상태관리의 기술적인 불편한점이 존재
- 자손 페이지가 생기면, 계속해서 전달해나가며 유지해야함
- Redux의 도입으로 Store를 한 곳에서 관리 및 dispatch로 상태 관리
> Feat: Create SignUpPage, Add AuthStore using redux

- Gasip Front/Components/HomeScreen.js
- Gasip Front/Components/MyPageScreen.js
- Gasip Front/Components/MyPageStack.js
- Gasip Front/Components/ProfList.js
- Gasip Front/Components/SignInPage.js
- Gasip Front/Components/SignUpPage.js
- Gasip Front/Components/ThemeStyle.js
- Gasip Front/Components/WritePage.js
- Gasip Front/Layout/layout.js
- Gasip Front/Utils/AuthFunc.js
- Gasip Front/Utils/AuthHooks.js
- Gasip Front/eas.json
- SignInPage.js : 로그인 페이지 구현
- 사용자 인증을 위한 함수와 커스텀훅 분리 
- AuthFunc.js : 사용자 인증을 위한 함수 
- AuthHooks.js : 사용자 인증을 위한 커스텀훅
- 나머지 컴포넌트에도 커스텀훅 적용 
- MyPageScreen.js 
- MyPageStack.js 
- SignUpPage.js
- 사용자 인증 테스트를 위한 Fake API 이용
- 로그인 페이지 구현
- 사용자 인증에 필요한 함수와 커스텀훅 설계
- Fake API를 이용한, 사용자 인증 테스트
#84 
- 재사용되는 사용자 인증 관련 함수들과 `react-redux`의 `dispatch`들이 난잡하게 퍼져있는 것을 정리할 필요성 존재.
- 커스텀훅을 설계하여, 재사용할 수 있도록 구성.
> Feat: 사용자 로그인 페이지 구현 및 커스텀훅 적용

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
- src/main/java/com/example/gasip/board/model/Board.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/college/service/CollegeService.java
- src/main/java/com/example/gasip/professor/model/Professor.java
- Board 조회 시 profId 안나오는 오류 해결
> Refactor: Board 조회 시 profId 안나오는 오류 해결

- src/main/java/com/example/gasip/member/service/MemberService.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
- findAll 시 stream 적용
#99 
- findAll 사용 시 DB fk가 null인 경우 런타임에러 발생
- 쿼리DSL로 변경하거나, 예외처리 프로세스를 별도로 가져가야할지 학습 필요
> Refactor: findAll 시 stream 적용

- src/main/generated/com/example/gasip/board/model/QBoard.java
- src/main/java/com/example/gasip/board/model/Board.java
- src/main/java/com/example/gasip/comment/model/Comment.java
- src/main/java/com/example/gasip/global/constant/ErrorCode.java
- src/main/java/com/example/gasip/global/exception/handler/GlobalControllerAdvice.java
-  댓글 삭제 시 부모 댓글 및 게시글 전부 삭제되는 버그 해결
#108
> refactor : 댓글 삭제 시 부모 댓글 및 게시글 전부 삭제되는 버그 해결

- src/main/java/com/example/gasip/board/dto/BoardDetailResponse.java
- professor 프록시 객치 매핑 불가한 부분 해결
- professor -> profId 가져오는 것으로 변경
#112
> refactor : BoardDetailResponse 리팩토링

- src/main/java/com/example/gasip/comment/repository/CommentRepository.java
- src/main/java/com/example/gasip/comment/service/CommentService.java
- src/main/java/com/example/gasip/major/controller/MajorController.java
- 서비스 단에서 if/else 문으로 해결
- Repository에서 JPA로 해결할 수 있는 방법이 있는지 확인 필요
#112 
- Repository단에서 쿼리로 해결한 것이 아닌 서비스 단에서 if/else 문으로 해결한 상태 : 더 좋은 방법이 있는지 확인 필요
- 레퍼런스 조회
> refactor : 댓글 조회 시 무조건 succss로 처리되는 에러 해결

- src/main/java/com/example/gasip/member/controller/MemberController.java
- src/main/java/com/example/gasip/member/service/MemberService.java
- isAuthenticated 메서드 개발
#118 
토큰 유효성 isAuthenticated 체크 시, 실패할 땐 filter에 걸려서 401 에러 코드말고는 별도 값을 호출하지 않음
프론트에서는 401 코드만 보고 토큰이 만료됐다고 확인해야함
이는 명확하지 않은 에러 코드로 추후 유지보수성 문제
고민중..
> Feat : 토큰 만료여부 체크 메서드 개발

- src/main/generated/com/example/gasip/likes/model/QLikes.java
- src/main/java/com/example/gasip/config/SecurityConfig.java
- 비로그인 사용자 조회 가능한 기능 SecurityConfig에서 permit
#124
> Feature/#124 비로그인 사용자 조회 가능 기능 정리

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/college/dto/CollegeDto.java
- src/main/java/com/example/gasip/college/dto/CollegeResponse.java
- src/main/java/com/example/gasip/college/model/College.java
> Feature/#122 게시글 페이지네이션

- src/main/java/com/example/gasip/board/repository/BoardRepository.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- Pageable 코드 추가
- 엔드포인트 변경
#122
> Feat : Board findAll 페이지네이션

- Gasip Front/Components/HomeScreen.js
- Gasip Front/Components/MyPageStack.js
- Gasip Front/Utils/AuthFunc.js
- Gasip Front/Utils/AuthHooks.js
- Gasip Front/Utils/Configuration.js
- Add CheckToken Function in AuthFunc.js
- Add useEffect checking token in MyPageStack.js
- 토큰을 이용한 사용자 로그인 체크
- 만료된 토큰일 시에 로그아웃 처리
close #128 
- Token을 이용한 사용자 인증 API가 없었기에, 해결방법에 대한 고민
- 백엔드와 협조해서 API를 구현 후 로직 구현
> Feat: Authentification by Token Checking

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/model/Board.java
- src/main/java/com/example/gasip/board/repository/BoardRepository.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/config/SecurityConfig.java
- 교수id별 게시글 조회 api 개발
- 교수id별 게시글 조회 & 전체 게시글 조회 pageing 처리
#131
> Feature/#131 교수id별조회

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/repository/BoardRepository.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/config/SecurityConfig.java
- 게시글 조회 시 최신 피드 순으로 조회
- JWT 토큰 없어도 조회는 가능하도록 변경
#122
> Feat : 게시글 전체 조회 페이지네이션 적용

- src/main/java/com/example/gasip/freefeed/controller/FreefeedController.java
- src/main/java/com/example/gasip/freefeed/dto/FeedCreateRequest.java
- src/main/java/com/example/gasip/freefeed/dto/FeedCreateResponse.java
- src/main/java/com/example/gasip/freefeed/model/Freefeed.java
- src/main/java/com/example/gasip/freefeed/repository/FreefeedRepository.java
- src/main/java/com/example/gasip/freefeed/service/FreefeedService.java
- FreeFeed 도메인 생성
- Create 로직 개발
#133
> Feat : 자유게시판 글 작성 api 개발

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/model/Board.java
- src/main/java/com/example/gasip/board/repository/BoardRepository.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- 좋아요 수 순으로 내림차순하여 5개 제시
- 페이지네이션 활용하여 5개만 불러오도록 개발
#136 
- 좋아요 수 같을 시 우선순위 처리 로직 개발 필요
- 회의 후 우선순위 정하는 기획 진행
> Feat : Board 교수별 베스트 게시글 조회 api 개발

- src/test/java/com/example/gasip/board/controller/BoardControllerTest.java
> Feat : Board Test 클래스 생성

- build.gradle
- src/main/java/com/example/gasip/board/dto/BoardCreateResponse.java
- src/main/java/com/example/gasip/board/repository/BoardRepository.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/college/model/College.java
- src/main/java/com/example/gasip/global/security/WithMockMember.java
- src/main/java/com/example/gasip/global/security/WithMockMemberSecurityContextFactory.java
- src/main/java/com/example/gasip/major/model/Major.java
- src/main/java/com/example/gasip/member/model/Member.java
- src/test/java/com/example/gasip/board/controller/BoardControllerTest.java
- 컨트롤러 테스트 코드 추가
- 베스트 게시글 개선(좋아요 수 동일 시 조회수로 정렬)
> Feature/#133 전체게시글등록

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/dto/BoardReadResponse.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/category/controller/CategoryController.java
- src/main/java/com/example/gasip/comment/controller/CommentController.java
- src/main/java/com/example/gasip/config/SecurityConfig.java
- src/main/java/com/example/gasip/global/swagger/swaggerConfig.java
- src/main/java/com/example/gasip/likes/controller/LikeController.java
- src/main/java/com/example/gasip/major/controller/MajorController.java
- src/main/java/com/example/gasip/member/controller/MemberController.java
- src/main/java/com/example/gasip/professor/controller/ProfessorController.java
- src/main/java/com/example/gasip/professordetail/controller/ProfessorDetailController.java
Reverts GASIP-PROJECT/gasip-service#149
> Revert "Feature/#129 swagger jwt"

- src/main/java/com/example/gasip/board/dto/BoardUpdateResponse.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/test/java/com/example/gasip/board/controller/BoardControllerTest.java
> Feat : Board 컨트롤러 유닛 테스트 작성

- build.gradle
- src/main/java/com/example/gasip/GasipApplication.java
- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/board/service/RedisViewCountService.java
- src/main/java/com/example/gasip/global/config/QuerydslConfig.java
- src/main/java/com/example/gasip/global/config/SecurityConfig.java
- src/main/java/com/example/gasip/global/exception/BoardNotFoundException.java
- src/main/java/com/example/gasip/global/exception/CommentNotFoundException.java
- src/main/java/com/example/gasip/global/exception/DuplicateResourceException.java
- src/main/java/com/example/gasip/likes/service/LikeService.java
- src/test/java/com/example/config/SecurityConfigTest.java
- src/test/java/com/example/gasip/board/controller/BoardControllerTest.java
- 최초 1회, 1명의 유저가 Board(게시글) 에 접근하면 조회수 1 증가
- 5분 내 다시 접근하면 조회수 증가X
- Redis를 이용하여 구현
#153 
- 비회원이 게시글 조회 시 조회수 무한 증식 가능한 상탶
- 쿠키 Or 세션으로 구분하는 로직 추가
> Refactor : 1개 계정으로 5분 내 조회수 중복 증가 불가 로직 구현

- build.gradle
- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/model/Board.java
- src/main/java/com/example/gasip/board/service/BoardLockFacade.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/test/java/com/example/gasip/board/service/BoardServiceTest.java
- 조회수 클릭 시 Facade 패턴 기반 분산락 구현
#156 
- 분산락 적용 시 속도 이슈 (500개 동시 조회 시 24초)
- sync schdule 적용
> Refactor/#156 분산락구현

- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/board/service/RedisViewCountService.java
- Redis 접근 후 데이터 조회&삭제를 원자적으로 진행
#159
> Refactor : 1,2씩 조회수 유실되는 버그 해결

- build.gradle
- src/main/java/com/example/gasip/grade/controller/GradeController.java
- src/main/java/com/example/gasip/grade/dto/request/GradeCreateRequest.java
- src/main/java/com/example/gasip/grade/dto/response/GradeCreateResponse.java
- src/main/java/com/example/gasip/grade/model/Grade.java
- src/main/java/com/example/gasip/grade/repository/GradeRepository.java
- src/main/java/com/example/gasip/grade/service/GradeService.java
- 도메인 생성
- Board 도메인 내 평점 도메인 분리 필요
#154 
Board 내 평점 기능 분리 필요
> Feat : 평점 도메인 분리

- src/main/generated/com/example/gasip/category/dto/QCategoryResponse.java
- src/main/java/com/example/gasip/board/dto/BoardReadRequest.java
- src/main/java/com/example/gasip/category/controller/CategoryController.java
- src/main/java/com/example/gasip/category/dto/CategoryResponse.java
- src/main/java/com/example/gasip/category/model/Category.java
- src/main/java/com/example/gasip/category/repository/CategoryRepository.java
- src/main/java/com/example/gasip/category/repository/CategoryRepositoryCustom.java
- src/main/java/com/example/gasip/category/repository/CategoryRepositoryCustomImpl.java
- src/main/java/com/example/gasip/category/service/CategoryService.java
- Category 내 단과대 목록 불러오는 API 추가
- College Category API 병합
- Category 테이블 내 단과대 id를 통한 단과대 목록 조회
#162 
- 쿼리 dsl 적용 시 fromEntity 호출 시 에러
- 해당 부분 보완 필요
> College Category 테이블 내 단과대 데이터 중복으로 인한 API 병합

- src/main/java/com/example/gasip/board/dto/BoardCreateRequest.java
- src/main/java/com/example/gasip/board/dto/BoardCreateResponse.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/grade/controller/GradeController.java
- src/main/java/com/example/gasip/grade/dto/request/GradeCreateRequest.java
- src/main/java/com/example/gasip/grade/dto/response/GradeGetDto.java
- src/main/java/com/example/gasip/grade/dto/response/GradeGetResponse.java
- src/main/java/com/example/gasip/grade/model/Grade.java
- src/main/java/com/example/gasip/grade/repository/GradeRepository.java
- src/main/java/com/example/gasip/grade/repository/GradeRepositoryCustom.java
- src/main/java/com/example/gasip/grade/repository/GradeRepositoryCustomImpl.java
- src/main/java/com/example/gasip/grade/service/GradeService.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
- src/test/java/com/example/gasip/board/controller/BoardControllerTest.java
> Feature/#154 평점도메인구성

- deploy.sh
> Refactor : deploy.sh 변경

- .github/workflows/gradle.yml
> EC2 CD 테스트

- Dockerfile
- build.gradle
- src/main/resources/logback.xml
- 디스코드 의존성 추가
- 웹훅 xml 파일 작성
#189
> Feat : 디스코드 웹훅 적용

- Dockerfile
- build.gradle
- src/main/java/com/example/gasip/category/repository/CategoryRepositoryCustomImpl.java
- src/main/resources/logback.xml
- 디스코드 의존성 추가
- 웹훅 관련 xml 파일 추가
#189
> 디스코드 웹훅 설정 추가

- build.gradle
> Refactor : 디스코드 웹훅 적용

- build.gradle
> 디스코드 logback.xml 파일 수정

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/comment/controller/CommentController.java
- src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
- src/main/java/com/example/gasip/comment/service/CommentService.java
- src/main/java/com/example/gasip/global/constant/ErrorCode.java
- src/main/java/com/example/gasip/global/exception/BaseException.java
- src/main/java/com/example/gasip/global/exception/BoardNotFoundException.java
- src/main/java/com/example/gasip/global/exception/DuplicateGradeCreateException.java
- src/main/java/com/example/gasip/global/exception/InvaildWritterException.java
- src/main/java/com/example/gasip/global/exception/InvalidGradePointException.java
- src/main/java/com/example/gasip/global/exception/MemberNotFoundException.java
- src/main/java/com/example/gasip/global/exception/ProfessorNotFoundException.java
- src/main/java/com/example/gasip/grade/service/GradeService.java
- src/main/java/com/example/gasip/member/service/MailService.java
- src/main/java/com/example/gasip/member/service/MemberService.java
> Refactor : 예외처리 리팩토링

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/repository/BoardRepository.java
- src/main/java/com/example/gasip/board/service/BoardService.java
교수 게시글 조회 로직 누락으로 Board 도메인에 로직 추가
#215
> HotFix : 교수별 게시글 조회 로직 누락으로 추가

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- queryDSL 기반 좋아요 순 내림차순으로 정렬
#221
> Refactor : 전체 인기글 조회로 변경

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/repository/BoardRepository.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/professor/controller/ProfessorController.java
- src/main/java/com/example/gasip/professor/repository/ProfessorRepository.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
검색 기능 사용 시 요청 날짜 기준 최근 글이 가장 상단으로 조회되도록 변경
#224
> [백엔드] 검색 기능 사용 시 내림차순 정렬

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/global/constant/ErrorCode.java
- src/main/java/com/example/gasip/global/exception/MemberDuplicatedException.java
- src/main/java/com/example/gasip/member/controller/MemberController.java
- src/main/java/com/example/gasip/member/dto/MemberSignUpRequest.java
- src/main/java/com/example/gasip/member/dto/MemberSignUpResponse.java
- src/main/java/com/example/gasip/member/model/Member.java
- src/main/java/com/example/gasip/member/service/MemberService.java
- 와이어프레임 기반하여, 회원가입 시 닉네임 값도 필수로 받도록 작성
#230
> Feat : 회원가입 시 닉네임 칼럼 추가

- src/main/java/com/example/gasip/member/controller/MemberController.java
- src/main/java/com/example/gasip/member/dto/MemberSignUpRequest.java
- src/main/java/com/example/gasip/member/dto/MemberSignUpResponse.java
- src/main/java/com/example/gasip/member/dto/MemberUpdateNicknameRequest.java
- src/main/java/com/example/gasip/member/dto/MemberUpdateNicknameResponse.java
- src/main/java/com/example/gasip/member/model/Member.java
- src/main/java/com/example/gasip/member/service/MemberService.java
> Feat : 닉네임 변경 로직 구현

- src/main/java/com/example/gasip/member/controller/MemberController.java
- src/main/java/com/example/gasip/member/dto/MemberUpdatePasswordRequest.java
- src/main/java/com/example/gasip/member/dto/MemberUpdatePasswordResponse.java
- src/main/java/com/example/gasip/member/model/Member.java
- src/main/java/com/example/gasip/member/service/MemberService.java
- 닉네임 변경
- 비밀번호 변경
- 회원 탈퇴(hard delete)
#239
> Feat : 닉네임 변경, 비밀번호 변경, 회원 탈퇴 로직 추가

- src/main/java/com/example/gasip/member/controller/MemberController.java
- 닉네임 변경
- 비밀번호 변경
- 회원 탈퇴(hard delete)
#239
> Feat : 스웨거 태그 추가

- src/main/java/com/example/gasip/global/config/SecurityConfig.java
> HotFix : CORS 에러 해결

- src/main/java/com/example/gasip/professor/controller/ProfessorController.java
> Feat : profId로 교수 조회 시 게시글에 교수 정보 포함해서 호출하는 기능 구현

- src/main/java/com/example/gasip/likes/dto/LikeRequestDto.java
좋아요 요청 시 헤더에서 memberId 받도록 수정
#203
> [백엔드] Refacor : 좋아요 요청 시 헤더에서 memberId 받도록 수정

- src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
Board 상세정보 호출 시 닉네임 칼럼 추가
#271
> HotFix : Board 상세정보 호출 시 닉네임 칼럼 추가

- src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
- BoardReadResponse 파라미터 추가
- 생성자 주입 방식으로 인한 QueryDSL 내 파라미터 수정
> publish : BoardReadResponse Q파일 수정

- src/main/java/com/example/gasip/member/controller/MemberController.java
- src/main/java/com/example/gasip/member/service/MemberService.java
- 이미 가입한 이메일도 비밀번호 설정할 수 있도록 인증번호 전송
#283
> Feat : 비밀번호 재설정 시 이메일 인증 api

- src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
- 이미 가입한 이메일도 비밀번호 설정할 수 있도록 인증번호 전송
> publish : 기존이메일인증로직 배포

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/commentLikes/controller/CommentLikesController.java
- src/main/java/com/example/gasip/commentLikes/dto/CommentLikesRequestDto.java
- src/main/java/com/example/gasip/commentLikes/model/CommentLikes.java
- src/main/java/com/example/gasip/commentLikes/repository/CommentLikesRepository.java
- src/main/java/com/example/gasip/commentLikes/service/CommentLikesService.java
- src/main/java/com/example/gasip/global/redisson/CustomSpringELParser.java
- src/main/java/com/example/gasip/global/redisson/RedissonLock.java
- src/main/java/com/example/gasip/global/redisson/RedissonLockAspect.java
- src/main/java/com/example/gasip/likes/service/LikeServiceInRedis.java
- src/main/java/com/example/gasip/member/controller/MemberController.java
- src/main/java/com/example/gasip/member/service/MemberService.java
- Board에 포함된 모든 칼럼 추가
- reddison 위치 조장
#286 
- 코드 최적화 필요
- 쿼리DSL로 호출 시 BoardReadResponse 타입으로 받아서 다시 Board로 돌렸다가 다시 BoardReadResponse로 되돌리는 비효율 존재
- 쿼리DSL 응답 타입 조정
> Feat : CommentLike 도메인생성 및 내가쓴글 응답 정보 추가

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/dto/OneBoardReadResponse.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/commentLikes/controller/CommentLikesController.java
- src/main/java/com/example/gasip/commentLikes/dto/CommentLikesRequestDto.java
- src/main/java/com/example/gasip/commentLikes/model/CommentLikes.java
- src/main/java/com/example/gasip/commentLikes/repository/CommentLikesRepository.java
- src/main/java/com/example/gasip/commentLikes/service/CommentLikesService.java
- src/main/java/com/example/gasip/global/redisson/CustomSpringELParser.java
- src/main/java/com/example/gasip/global/redisson/RedissonLock.java
- src/main/java/com/example/gasip/global/redisson/RedissonLockAspect.java
- src/main/java/com/example/gasip/likes/service/LikeServiceInRedis.java
- src/main/java/com/example/gasip/member/controller/MemberController.java
- src/main/java/com/example/gasip/member/service/MemberService.java
> publish 마이페이지응답정보변경 배포

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/member/service/MemberService.java
- 인기글 조회 시 좋아요 5개 이상 게시글 최신순으로 나오도록 정렬
- commentCount,isLike null 값 뜨던 버그 해결
- - 인증번호 로직 내 이메일 중복 확인 로직 제거
#292 
- null 값 처리하는 과정에서 최적화 필요
> Feature/#292 인기글응답칼럼수정

- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
- src/main/java/com/example/gasip/commentLikes/repository/CommentLikesRepository.java
게시글 조회 시 isCommentLike 칼럼에 올바른 값 들어오도록 수정
#282 
CommentReadResponse에서 isCommentLike 값을 어떻게 갱신해야 할 지? 
CommentReadResponse 빈 리스트 생성 후 Comment에서 값 갱신 후 add
> [백엔드] 게시글 조회 시 isCommentLike 칼럼 추가

- src/main/java/com/example/gasip/professor/service/ProfessorService.java
- findProfessorByProfNameLike 로직 수정
#296
> HotFix : 교수 String 검색 시 교수평점 안나오는 에러 해결

- src/main/java/com/example/gasip/grade/repository/GradeRepository.java
- src/main/java/com/example/gasip/professor/controller/ProfessorController.java
- src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
- src/main/java/com/example/gasip/professor/model/Professor.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
- findProfessorByProfNameLike 로직 내 isGrade 칼럼 추가
#296
> HotFix : 교수 String 검색 시 평점 등록 여부 칼럼 추가

- src/main/java/com/example/gasip/grade/repository/GradeRepository.java
- src/main/java/com/example/gasip/professor/controller/ProfessorController.java
- src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
- src/main/java/com/example/gasip/professor/model/Professor.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
> publish : isGrade 칼럼 추가

- src/main/java/com/example/gasip/professor/controller/ProfessorController.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
- findByProfId 로직 내 isGrade 칼럼 추가
> HotFix : 교수 Id 검색 시 평점 등록 여부 칼럼 추가

- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/comment/dto/CommentChildrenReadResponse.java
- src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
- 게시글 호출 시 CommentLike 필드에 올바른 값 들어오도록 수정
- 게시글 호출 시 대댓글 isComment 필드에 null값 들어오는 문제 수정
#282 
대댓글에 null 값이 왜 들어가는지 찾는 과정에서 꽤 오랜시간 해맴
- for문 안에서 commentDto 값을 처리해서 대댓글 값이 누락되는 것을 확인.
- for문이 끝난 후 처리하도록 수정
> [백엔드] HotFix 게시글 호출 시 댓글 필드 수정

- src/main/java/com/example/gasip/member/dto/MemberLogInResponse.java
- MemberLogInResponse에 nickname 필드 추가
- 로그인 시 반환 컬럼에 nickname 필드 추가
#307
> Refactor : 추가 nickname 필드

- src/main/java/com/example/gasip/comment/dto/CommentChildrenReadResponse.java
- CommentChildrenReadResponse dto 내 응답 칼럼으로 nickName 추가
#292
> Refactor : 대댓글 응답 데이터에 닉네임 추가

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/repository/BoardRepository.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- Board 도메인 리팩토링(가독성 확보 작업)
- 대댓글 응답 컬럼 추가(유저 닉네임)
> 리팩토링 내역 배포

- src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
- 닉네임 칼럼에 사용자 이름이 출력되는 버그 해결
#292
> Refactor : 댓글 응답데이터 수정

- src/main/java/com/example/gasip/comment/dto/CommentReadResponse.java
- src/main/java/com/example/gasip/member/controller/MemberController.java
- src/main/java/com/example/gasip/member/dto/MemberResetPasswordRequest.java
- src/main/java/com/example/gasip/member/dto/MemberResetPasswordResponse.java
- src/main/java/com/example/gasip/member/service/MemberService.java
> 로그인화면에서 비밀번호 변경 로직 추가하여 배포

- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
Resolves: #307
findAllByMemberId regDate 기준 내림차순 정렬으로 변경
#317
> Refactor : 추가 regDate 기준 내림차순 정렬

- src/main/java/com/example/gasip/professor/controller/ProfessorController.java
- src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
- src/main/java/com/example/gasip/professor/repository/ProfessorRepositoryCustom.java
- src/main/java/com/example/gasip/professor/repository/ProfessorRepositoryCustomImpl.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
학과/전공 키워드를 통한 교수 검색 기능 구현
#320
> [백엔드] 학과/전공 키워드를 통한 교수 검색 기능 

- src/main/java/com/example/gasip/professor/service/ProfessorService.java
Resolves: #326
전체 검색 시 response 데이터에 null 값 return 하도록 변경
#326
> Refactor : 추가 전체 검색 시 response 데이터에 null 값 return

- src/main/java/com/example/gasip/professor/service/ProfessorService.java
Resolves: #326
- ProfessorService 내 findProfessorByProfessorNameLike 리팩토링
- 교수 평균평점과 로그인 사용자의 평가여부 체크
#326 
- 검색 속도가 너무 느려 개선 필요
> Refactor : 추가 교수 검색 시 averageGradePoint 칼럼 추가

- src/main/java/com/example/gasip/professor/controller/ProfessorController.java
Resolves: #326
- api url search에서 prof-search로 변경
- prof-search 문서 추가
#326
> Refactor, Doc : 변경 /search -> /prof-search, 추가 prof-search Doc

- README.md
- src/main/java/com/example/gasip/grade/repository/GradeRepositoryCustomImpl.java
- src/main/java/com/example/gasip/professor/controller/ProfessorController.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
- 모든 교수 리뷰 불러오는 기능 추가 "professor-boards"
- 모든 자유게시글 불러오는 기능 추가 "free-boards"
#332 
- Dto를 Entity로 변환하는 과정이 어려웠음
- 빈 리스트 생성 후 매핑
> 모든 교수 리뷰 불러오는 기능, 모든 자유 게시글 불러오는 기능 추가

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
- src/main/java/com/example/gasip/board/service/BoardService.java
모든 교수 리뷰, 자유 게시글 reponse에 isLike 칼럼 추가
#332
> 모든 교수 리뷰, 자유 게시글 reponse에 isLike 칼럼 추가

- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustom.java
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- findFreeBoardByProfessor, findBoardByAllProfessor 페이지네이션 추가
#337
> [백엔드] findFreeBoardByProfessor, findBoardByAllProfessor 페이지네이션 추가

- src/main/java/com/example/gasip/grade/repository/GradeRepositoryCustomImpl.java
- src/main/java/com/example/gasip/professor/controller/ProfessorController.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
모든 교수 리뷰, 자유게시판에 페이지네이션 추가
#337
> 모든 교수 리뷰, 자유게시판에 페이지네이션 추가 및 리팩토링

- src/main/java/com/example/gasip/board/service/BoardService.java
- 게시글 검색 api에 readOnly 추가
#342 
- 게시글 내용 검색 api 400에러 발생 상황
- 포스트맨 url 에러로 확인 완료.(코드 문제 없음)
> Refactor : 트랜잭션 ReadOnly 추가

- .gitignore
- build.gradle
- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/dto/BoardPushRequest.java
- src/main/java/com/example/gasip/board/service/FirebasePushService.java
- src/main/java/com/example/gasip/global/entity/FcmMessage.java
- 게시글 알림 api 개발
- firebase 의존성 추가
#347 
1. 프론트에서 accessToken 발급방법 확인 필요
> Feat : firebase 의존성 추가

- .gitignore
- build.gradle
- deploy.sh
- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/dto/BoardPushRequest.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/board/service/FirebasePushService.java
- src/main/java/com/example/gasip/global/entity/FcmMessage.java
> publish : deploy.sh 수정

- README.md
- 스레드 풀 테스트를 위해 main 브랜치 merge용 임시 변경
- 스레드 풀 사이즈 400 -> 100으로 축소
- 서버 상황에 최적인 스레드 풀을 찾는 방법 확인 필요
> publish : 스레드 풀 변경 테스트

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/dto/BoardPushRequest.java
- src/main/java/com/example/gasip/board/dto/FcmMessageRequest.java
- src/main/java/com/example/gasip/board/service/FirebasePushService.java
- 프론트 측 요청 api 구현
- FCM 서버에 요청하는 api 구현
#347 
1. 프론트 측에서 유효한 디바이스 토큰을 줬을 때 실제로 동작하는지 확인 필요
1. 프론트 코드 구현 후 서버 레벨에서 테스트 수행
https://adjh54.tistory.com/432
> Feat : FCM 알림 기능 구현

- .gitignore
- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
- src/main/java/com/example/gasip/category/dto/CategoryDto.java
- src/main/java/com/example/gasip/category/dto/CategoryResponse.java
- src/main/java/com/example/gasip/category/model/Category.java
- src/main/java/com/example/gasip/category/repository/CategoryRepository.java
- src/main/java/com/example/gasip/category/repository/CategoryRepositoryCustomImpl.java
- src/main/java/com/example/gasip/category/service/CategoryService.java
- category 조회 api 구현 및 리팩토링
#359 
- Querydsl 사용 시 한글, 영어 순으로 배열하는 방법 찾지 못 함
- asc() 사용 시 한글, 영어순으로 정렬됨
> Refactor : category 조회 api 구현 및 리팩토링

- src/main/java/com/example/gasip/board/service/BoardService.java
> Feat : 인기글 등록 하루 초과 시 인기글에서 제외

- src/main/java/com/example/gasip/grade/dto/response/GradeGetDto.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
> HotFix : 교수 평점 소수점 버그 픽스

- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/grade/dto/response/GradeGetDto.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
> publish : 교수 평점 소수점 에러 픽스

- src/main/java/com/example/gasip/professor/service/ProfessorService.java
> HotFix : 게시글 조회 버그 픽스

- src/main/java/com/example/gasip/grade/dto/response/GradeGetDto.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
> publish : 게시판 조회 버그 픽스

- src/main/java/com/example/gasip/grade/dto/response/GradeGetDto.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
- null인 경우 평균평점이 0으로 나오도록 수정
#366
> HotFix : 평균 평점 로직 수정

- src/main/java/com/example/gasip/grade/dto/response/GradeGetDto.java
- src/main/java/com/example/gasip/professor/service/ProfessorService.java
- 교수 평점이 null인 경우 고려하여 로직 수정
#366
> publish : 평균 평점 조회 로직 bugfix

- src/main/java/com/example/gasip/global/config/SecurityConfig.java
> HotFix : 비밀번호 재설정 로직 호출 수정

- src/main/java/com/example/gasip/global/config/SecurityConfig.java
> Bug : 자유게시판 조회 버그 해결

- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
- 커버링 인덱스 사용 시 1페이지 이상 조회되지 않는 버그 해결
#377
> Bug Fix : 커버링 인덱스 사용 시 1페이지 이상 조회되지 않는 버그

- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
자유게시판 size마다 게시글 달라지는 버그 수정
#377
> Fix : 자유게시판 size마다 게시글 달라지는 버그 수정

- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
자유게시판 페이지 별 조회 목록 달라지는 버그 수정
#377
> Publish : 자유게시판 페이지 별 조회 목록 달라지는 버그 수정

- build.gradle
- src/main/java/com/example/gasip/board/service/FirebasePushService.java
- src/main/java/com/example/gasip/global/config/AsyncConfig.java
- 알림 전송 로직 비동기로 변경
- 별도 알림 전용 스레드 풀 생성
#383
> #383 알림비동기구현

- .github/workflows/stage.yml
> CICD 파이프라인 테스트

- .github/workflows/gradle.yml
> fix key value

- scripts/start.sh
- scripts/stop.sh
> Edit Path variables

- appspec.yml
> fix : appspec.yml 변경

- build.gradle
- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/service/FirebasePushService.java
- src/main/java/com/example/gasip/professor/controller/ProfessorController.java
- src/main/java/com/example/gasip/professor/dto/ProfessorCrawlRequest.java
- src/main/java/com/example/gasip/professor/service/ProfessorDataCrawlingService.java
- src/test/java/com/example/gasip/board/service/BoardServiceTest.java
- Jsoup 의존성 추가
- dto에 학과번호 추가
#414
> Feat : 교수정보 크롤링 api 뼈대 생성

- src/main/resources/logback-dev.xml
Resolves: #416
- 디스코드 웹 훅 추가 테스트
> feat : stage 서버 디스코드 웹 훅 추가

- .github/workflows/stage.yml
> stage.yml 수정

- src/main/resources/logback-dev.xml
Resolves: #416
- 변경 application.yml 참조
> fix : 변경 application.yml

- .github/workflows/stage.yml
- src/main/resources/logback-dev.xml
- 디스코드 웹 훅 버그 수정
- logback 코드 수정
#416
> 디스코드 웹 훅 버그 수정

- src/main/resources/logback-dev.xml
- src/main/resources/logback.xml
> fix : 변경 logback.xml

- src/main/resources/logback-dev.xml
- src/main/resources/logback.xml
> 변경 logback.xml

- scripts/start.sh
Resolves: #416
- error.log 작성되도록 변경
#416
> fix : error.log 추가

- scripts/start.sh
Resolves: #416
- start.sh 변경
#416
> fix : start.sh 변경

- scripts/start.sh
> start.sh 변경

- scripts/start.sh
- start.sh 변경
- nohup 배포 시 로그 기록 임시 삭제
#416
>  nohup 배포 시 로그 기록 임시 삭제

- scripts/start.sh
- jar 파일 배포 시 dev 환경에서 실행되도록 변경 
#416
> 배포 시 dev 환경에서 실행되도록 변경 

- scripts/start.sh
Resolves: #416
- 배포 시 디스코드 웹 훅 작동되지 않는 문제 해결
- 배포시 dev 환경에서 실행
- log 파일 추가
#416 
- ec2 환경에서 배포 시 알림이 오지 않는 원인을 찾는라 힘들었음
- profiles.activate를 dev로 설정해주지 않아 알림이 오지 않았음
- 배포 시 --spring.profiles.active=dev 코드를 통해 dev 환경에서 실행되도록 설정
>  배포 시 디스코드 웹 훅을 통해 알림이 오지 않는 버그 수정

- src/main/resources/logback-dev.xml
- src/main/resources/logback.xml
- log-back.yml stage서버 디스코드 웹 훅 username 변경
- #435 
- 없음
> log-back.yml stage서버 username 변경

- scripts/start.sh
- src/main/resources/logback-dev.xml
- log-back.yml stage서버 디스코드 웹 훅 username 변경
- #435 
- 없음
> stage서버 디스코드 웹 훅 username 변경

- src/main/java/com/example/gasip/professor/service/ProfessorDataCrawlingService.java
- 가천대학교 교수 정보 페이지 정보 크롤링
#414 
1.Jsoup으론  교수님 졸업 학교 정보 크롤링 불가
1. 셀레니움 활용 방안 리서치
> Feat : 교수정보 크롤링 코드 추가

- src/main/java/com/example/gasip/professor/service/ProfessorDataCrawlingService.java
- src/main/resources/logback-dev.xml
> 교수 크롤링 데이터 배포

- build.gradle
- src/main/java/com/example/gasip/category/repository/CategoryRepository.java
- src/main/java/com/example/gasip/professor/dto/ProfessorCrawlRequest.java
- src/main/java/com/example/gasip/professor/model/Professor.java
- src/main/java/com/example/gasip/professor/repository/ProfessorRepository.java
- src/main/java/com/example/gasip/professor/service/ProfessorDataCrawlingService.java
- src/main/resources/logback.xml
- 가천대학교 교수 위치정보 필터링 로직 추가
- grafana & prometheus 의존성 추가
#414
> Feature/#414 교수정보크롤링

- .github/workflows/gradle.yml
- build.gradle
- src/main/java/com/example/gasip/category/repository/CategoryRepository.java
- src/main/java/com/example/gasip/professor/dto/ProfessorCrawlRequest.java
- src/main/java/com/example/gasip/professor/model/Professor.java
- src/main/java/com/example/gasip/professor/repository/ProfessorRepository.java
- src/main/java/com/example/gasip/professor/service/ProfessorDataCrawlingService.java
- src/main/resources/logback-dev.xml
- src/main/resources/logback.xml
- 가천대학교 교수 위치정보 필터링 로직 추가
- grafana & prometheus 의존성 추가
> stage : 모니터링 환경 의존성 추가

- scripts/start.sh
> Refacor : 서버 확인

- src/main/resources/logback-dev.xml
Resolves: #446
- stage 서버 디스코드 웹 훅 "운영 서버 에러"로 뜨는 버그 수정
- #447
> fix : stage 서버 디스코드 웹 훅 "운영 서버 에러"로 뜨는 버그 수정

- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- 현시점 기준 10일전 게시글까지 범위 확장 (IOS 앱 심사 때문)
#453
> Feat : 인기글 조회 로직 임시변경

- src/main/resources/logback-dev.xml
Resolves: #446
- stage서버 디스코드 웹 훅 logback-dev.yml 파일 못찾는 버그 수정
#456
> hotfix : stage서버 디스코드 웹 훅 버그 수정 

- src/main/java/com/example/gasip/professor/dto/ProfessorResponse.java
- src/main/java/com/example/gasip/professor/model/Professor.java
- Education 칼럼 추가
#414 
- Salanium 사용법 미숙
> Feat : Education 칼럼 추가

- src/main/java/com/example/gasip/board/service/BoardService.java
> publish : 인기글 로직 미변경 확인

- src/main/java/com/example/gasip/board/service/BoardService.java
> publish : 인기글 로직 임시설정 테스트

- appspec.yml
- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/service/BoardService.java
> publish : appspec.yml 수정

- deploy.sh
> Feat : deploy.sh 수정

- src/main/resources/logback.xml
> Feat : logback.xml 수정

- appspec.yml
Resolves: #468
stgae 서버 배포를 위해 appspec.yml 임시 변경
> fix : stgae 서버 배포를 위해 appspec.yml 임시 변경

- .github/workflows/stage.yml
- appspec.yml
- deploy.sh
- src/main/java/com/example/gasip/board/controller/BoardController.java
- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/member/service/MemberService.java
- src/main/resources/logback.xml
> publish : 회원가입 인증번호 코드 임시 고정

- appspec.yml
Resolves: #480
- main 서버 배포를 위한 appspec.yml 변경
#480
> publish : 배포 main 서버 배포를 위한 appspec.yml 변경

- src/main/java/com/example/gasip/board/model/Board.java
Resolves: #482
- deleted, gradepoint 필드 추가
#474
> feat : 추가 deleted, gradepoint

- README.md
- deleted, gradepoint 필드 추가
#474
> publish : deleted, gradepoint 필드 추가

- src/main/java/com/example/gasip/member/service/MemberService.java
Resolves: #486
변경 회원가입 인증번호 코드 임시 고정 해제
#486
> Refactor : 변경 회원가입 인증번호 코드 임시 고정 해제

- src/main/java/com/example/gasip/board/model/Board.java
- src/main/java/com/example/gasip/member/service/MemberService.java
> Publish : 회원가입 인증코드 임시 고정 해제

- src/main/java/com/example/gasip/board/service/BoardService.java
Resolves: #489
- 인기글 로직 정상화
#489
> Refactor : 변경 인기글 로직 정상화

- src/main/java/com/example/gasip/board/service/BoardService.java
- src/main/java/com/example/gasip/member/service/MemberService.java
> Publish : 인기글 로직 정상화

- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
Resolves: #482
- profId .eq를 통해 비교하도록 변경
#482
> bug : 변경 profId .eq를 통해 비교하도록

- appspec.yml
- 교수 상세페이지에 교수 정보와 다른 리뷰 노출되는 버그 수정
#482
> publish : 교수 상세페이지 게시글 노출 오류 수정

- appspec.yml
> publish : 재배포

- src/main/java/com/example/gasip/boardReport/controller/BoardReportController.java
- src/main/java/com/example/gasip/boardReport/model/BoardReport.java
- src/main/java/com/example/gasip/boardReport/service/BoardReportService.java
- src/main/java/com/example/gasip/commentReport/controller/CommentReportController.java
- src/main/java/com/example/gasip/commentReport/dto/CommentReportRequest.java
- src/main/java/com/example/gasip/commentReport/dto/CommentReportResponse.java
- src/main/java/com/example/gasip/commentReport/model/CommentReport.java
- src/main/java/com/example/gasip/commentReport/service/CommentReportService.java
- src/main/java/com/example/gasip/memberBlock/controller/MemberBlockController.java
- src/main/java/com/example/gasip/memberBlock/model/MemberBlock.java
- 게시글, 댓글 신고 및 유저 차단 API 명세 작성
- 신고 및 신고 취소 response 변경
#501
> Doc : 신고, 차단 명세서 작성

- src/main/java/com/example/gasip/board/service/BoardService.java
Resolves: #504
- 인기글 게시 기간 100일으로 설정
#504
> [백엔드] 인기글 게시 기간 100일으로 설정

- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
Resolves: #510
페이지네이션 성능 측정을 위한 커버링 인덱스 삭제 
#510
> refactor : 성능 테스트를 위한 커버링 인덱스 삭제

- src/main/java/com/example/gasip/board/repository/BoardRepositoryCustomImpl.java
> test: 커버링 인덱스를 통한 성능 개선

- deploy.sh
> refactor : owner 변경

- appspec.yml
- deploy.sh
> publish : prod 서버 배포

- README.md
> publish : prod 서버 재실행
